import {create} from 'domain';
import {title} from 'process';
import {StyleSheet} from 'react-native';
import {text} from 'stream/consumers';

export default StyleSheet.create({
  backgrounnnf: {
    flex: 1,
    backgroundColor: 'white',
  },
  iconsBar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  textBar: {
    fontSize: 52,
    flexDirection: 'row',
    justifyContent: 'space-around',
  },

  textHi: {
    color: 'Black',
    fontWeight: '500',
    fontSize: 20,
    margin: 15,
  },
  textİcon: {
    width: 23,
    height: 23,
    marginTop: 15,
  },
  iconUsers: {
    width: 32,
    height: 32,
    marginTop: 17,
    marginRight: 7,
  },
  exploreText: {
    color: 'grey',
    fontSize: 17,
    fontWeight: '300',
    marginLeft: 10,
  },
  searchAlani: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '90%',
    backgroundColor: 'white',
    padding: 11,
    borderRadius: 35,
    borderWidth: 1,
    borderColor: 'black',
    marginTop: 50,
    marginBottom: 5,
    marginLeft: 20,
  },
  search: {
    paddingLeft: 20,
    padding: 5,
    color: 'black',
    fontSize: 15,
  },
  searchBar: {
    fontSize: 52,
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginRight: 25,
  },
  textsembol: {
    fontSize: 23,
    width: 23,
    height: 23,
    marginleft: 20,
  },
  iconSearch: {
    width: 25,
    height: 25,
    marginTop: 1,
    marginRight: 7,
  },
  popular: {
    fontSize: 52,
    flexDirection: 'row',
    justifyContent: 'space-around',
    margin: 10,
  },
  textPopular: {
    fontSize: 26,
    color: 'Black',
    fontWeight: '500',
    margin: 15,
    marginRight: 70,

  },
  textView: {
    fontSize: 17,
    marginTop: 17,
    marginRight: 7,
    marginTop: 25,
  },
  Touchmost: {
    width: 130,
    height: 50,
    backgroundColor: 'black',
    borderRadius: 15,
    margin: 15,
    opacity: 0.8,
    marginLeft: 20,

  },
  textMost: {
    color: 'white',
    fontSize: 15,
    textAlign: 'center',
    marginTop: 15,
    marginRight: 5,
    fontWeight: '500',
  },
  Touchnear: {
    width: 130,
    height: 50,
    backgroundColor: 'white',
    borderRadius: 15,
    margin: 15,
    opacity: 0.3,
    marginLeft: 20,

  },
  textNearby: {
    color: 'black',
    fontSize: 15,
    textAlign: 'center',
    marginTop: 15,
    marginRight: 5,
    fontWeight: '500',
  },
  MostView: {
    flexDirection: 'row',
    justifyContent: 'space-between',

  },
  NearbyView: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  LatestTouch: {
    width: 130,
    height: 50,
    backgroundColor: 'white',
    color: 'white',
    borderRadius: 15,
    margin: 15,
    opacity: 0.3,
    marginLeft: 20,
  },
  textLatest:{
    color: 'black',
    fontSize: 15,
    textAlign: 'center',
    marginTop: 12,
    marginRight: 5,
    fontWeight: '500',
  },
  mountain: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    
    
  },
  mountainImage: {
    width: 250,
    height: 450,
    borderRadius: 20,
    margin: 15,
    marginLeft: 40,
  },
  mountainText: {
    color: 'black',
    fontSize: 20,
    fontWeight: '500',
    marginLeft: 40,
    position: 'absolute',
    marginTop: 70,
  },
  loveIcon: {
    width: 30,
    height: 30,
    marginTop: 15,
    marginLeft: 250,
    marginTop: 30,
    position: 'absolute',

  },
  locationArea: {
    height: 50,
    flexDirection: 'row',
    justifyContent: 'space-around',
    width: '70%',
    height: '17%',
    backgroundColor: '#0E1C43',
    padding: 11,
    borderRadius:15,
    borderWidth: 1,
    borderColor: 'black',
    marginTop: 360,
    marginleft: 90,
    marginBottom: 4,
    marginLeft: 58,
    position: 'absolute',
  },
  locationText: {
    color: 'white',
    fontSize: 15,
    fontWeight: '500',
    marginLeft: 70,
    marginTop: 370,
    position: 'absolute',
  },
  location: {
    width: 20,
    height: 20,
    marginTop: 400,
    marginLeft: 70,
    position: 'absolute',
    tintColor: 'white',
  },
  textLoca: {
    color: 'white',
    fontSize: 15,
    fontWeight: '500',
    marginLeft: 95,
    marginTop: 400,
    position: 'absolute',
  },
  starIcon: {
    width: 20,
    height: 20,
    marginTop: 400,
    marginLeft: 220,
    position: 'absolute',
    tintColor: 'white',
  },
  textStar: {
    color: 'white',
    fontSize: 15,
    fontWeight: '500',
    marginLeft: 240,
    marginTop: 400,
    position: 'absolute',
  },
  mountaintwo: {
    width: 300,
    height: 450,
    borderRadius: 20,
    margin: 15,
    marginRight: 40,
  },
  home: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 20,
  },
  hearth:{
    flexDirection: 'row',
    justifyContent: 'space-around',
  },
  homeIcon: {
    width: 30,
    height: 30,
    marginTop: 1,
    marginLeft: 25,
    marginTop: 40,
    //position: 'absolute',
  },
  clockIcon: {
    width: 30,
    height: 30,
    marginTop: 1,
    marginLeft: 85,
    marginTop: 40,
    //position: 'absolute',
  },
  lovIcon: {
    width: 30,
    height: 30,
    marginTop: 1,
    marginLeft: 100,
    marginTop: 40,
    //position: 'absolute',
  },
  userIcon: {
    width: 32,
    height: 32,
    marginTop: 40,
    marginRight: 12,
  },


  
});
